
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 26 13:01:07 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 11;
  public static final int READ = 6;
  public static final int IDENT = 25;
  public static final int PLUS = 7;
  public static final int RBRACE = 20;
  public static final int RPAREN = 18;
  public static final int EQUAL = 12;
  public static final int CHAR = 26;
  public static final int SEMI = 15;
  public static final int LBRACKET = 21;
  public static final int LBRACE = 19;
  public static final int LPAREN = 17;
  public static final int RBRACKET = 22;
  public static final int INC = 13;
  public static final int COMMA = 16;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int DIV = 10;
  public static final int PROG = 2;
  public static final int DEC = 14;
  public static final int MINUS = 8;
  public static final int CONST = 3;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int NEW = 4;
  public static final int BOOL = 24;
  public static final int MUL = 9;
}

